# -*- coding: utf-8 -*-
"""Ticket-Price.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AwnCa5Y80tyqpvvMojulIVzCB7hYr9mn

### 🎟️ Ticket Price Checker)
"""

import gradio as gr

custom_css = """
body {
    background: linear-gradient(135deg, #ffdde1, #ee9ca7);
    font-family: 'Poppins', sans-serif;
    text-align: center;
    color: #333;
}
.gradio-container {
    background-color: #ffffff;
    border-radius: 20px;
    box-shadow: 0 8px 20px rgba(0, 0, 0, 0.15);
    padding: 30px;
    max-width: 600px;
    margin: 100px auto;
}
h1 {
    color: #222;
}
button {
    background-color: #ff5e5e !important;
    color: white !important;
    font-size: 18px !important;
    border-radius: 10px !important;
    padding: 12px 20px !important;
    transition: 0.3s;
}
button:hover {
    background-color: #ff3838 !important;
    transform: scale(1.05);
}
"""

def code_like_yours(age):
    if age >= 18:
        return "Full price ticket: $12"
    else:
        return "Child discount: $5"


with gr.Blocks(css=custom_css, title="Ticket Price Checker") as demo:
    gr.Markdown("#Ticket Price Checker")
    gr.Markdown("Enter your age to find out your ticket price:")

    age = gr.Number(label="Enter Age", value=0)
    result = gr.Textbox(label="Result", placeholder="Your ticket price will appear here...")
    submit = gr.Button("Check Price")
    submit.click(fn=code_like_yours, inputs=age, outputs=result)

if __name__ == "__main__":
    demo.launch()

